name: my_portfolio
description: "A minimal portfolio website built with Flutter to showcase my projects and work."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  url_launcher: ^6.3.1
  shadcn_flutter: ^0.0.36
  go_router: ^16.0.0
  supabase_flutter: ^2.9.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/screenshots/
  